kind: Module
description: Ingress controller for garden development
name: ingress-controller
type: helm
repo: https://kubernetes.github.io/ingress-nginx
chart: ingress-nginx
releaseName: garden-nginx
dependencies:
  - default-backend
version: 3.19.0
values:
  name: ingress-controller
  controller:
    extraArgs:
      default-backend-service: ${var.namespace}/default-backend
    kind: DaemonSet
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    hostPort:
      enabled: true
      ports:
        http: ${var.ingress-http-port}
        https: ${var.ingress-https-port}
    minReadySeconds: 1
    tolerations: ${var.system-tolerations}
    nodeSelector: ${var.system-node-selector}
    admissionWebhooks:
      enabled: false
  defaultBackend:
    enabled: false
