name: Release the core npm package

on:
  release:
    types: [published]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  publish-npm-package:
    runs-on: macOS-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
      - name: Use Node.js 14.x
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e
        with:
          node-version: 14.x
      - name: Build package
        run: |
          yarn
          yarn build
      - name: Setup npm registry authentication
        working-directory: ./core
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Publish edge version if pre-release
        if: github.event.release.prerelease == true
        working-directory: ./core
        run: |
          CURRENT_CORE_VERSION=`node -e "console.log(require('./package.json').version);"`
          npm version $CURRENT_CORE_VERSION-edge.$SHORT_SHA
          npm publish --tag edge
      - name: Publish stable version if normal release
        if: github.event.release.prerelease != true
        working-directory: ./core
        run: |
          npm publish
